---
- hosts: pull_hosts
  become: yes
  roles:
    - { role: os_info, tags: [''] }
    - { role: ansible_pull, tags: [''] }
    - { role: aur_dir, tags: [''] }
    - { role: users, tags: [''] }
    - { role: locale, tags: [''] }
    - { role: time, tags: [''] }
    - { role: ssh, tags: [''] }
    - { role: yay_install, tags: [''] }
    - { role: reflector, tags: [''] }
    - { role: pacman, tags: [''] }
    - { role: pacman-repo, tags: [pacman-repo] }
