---
#- name: Enable redshift-gtk unit
#  systemd:
#    name: redshift-gtk
#    masked: no
#    scope: system
#    state: started
#  become: yes

- name: Enable lightdm unit
  systemd:
    name: lightdm.service
    masked: no
    scope: system
    state: started
    enabled: true
  become: yes

#- name: Reboot the {{ hostname }} to apply kernel and other updates
#  reboot:
#    reboot_timeout: 3600
#    test_command: whoami
#    msg: "Reboot initiated by Ansible to apply updates"
#  become: true
