- name: Install pkgfile
  pacman:
    name: pkgfile
    state: present

- name: Enable pkgfile timer
  systemd:
    name: pkgfile-update.timer
    enabled: True
  notify: Synchronise pkgfile database
