---
- name: "Clone yay AUR helper source git repository to {{ ansible_arch_yay.dest }}"
  git:
    repo: "{{ ansible_arch_yay.git }}"
    dest: "{{ ansible_arch_yay.dest }}"
    force: true

- name: "Set access rights to {{ ansible_arch_yay.owner.name }}:{{ ansible_arch_yay.owner.group }}"
  file:
    path: "{{ ansible_arch_yay.dest }}"
    state: directory
    mode: 0700
    owner: "{{ ansible_arch_yay.owner.name }}"
    group: "{{ ansible_arch_yay.owner.group }}"
    recurse: true

- name: Install required dependecies
  pacman:
    name: "binutils go base-devel"
    state: present

- name: "MAKEPKG yay AUR helper as {{ ansible_arch_yay.owner }}"
  shell: "makepkg -si --noconfirm > ./makepkg-yay.log"
  become: yes
  become_user: "{{ ansible_arch_yay.owner.name }}"
  args:
    chdir: "{{ ansible_arch_yay.dest }}"