- name: Update pacman cache
  pacman:
    update_cache: True

- name: Reload systemd daemon with systemd module
  systemd:
    daemon_reload: True
  listen: Reload systemd daemon

- name: Generate initramfs
  command: mkinitcpio --allpresets
