---
- name: Update the system {{ ansible_distribution | lower }}
  pacman:
    update_cache: yes
    upgrade: yes

- name: Install python-pip
  pacman:
    name: python-pip
    state: present
  become: true
  become_user: root

- name: Install python-setuptools
  pacman:
    name: python-setuptools
    state: present
  become: true
  become_user: root

- name: Install cronie
  pacman:
    name: cronie
    state: present
  become: true
  become_user: root

- name: Install git
  pacman:
    name: git
    state: present
  become: true
  become_user: root

- name: Install ansible with pip
  pip:
    name: ansible
  become: true
