---
- name: Ensure software-properties-common is instaled
  apt:
    name: "software-properties-common"
    state: present

- name: Install ansible ppa
  shell: "apt-add-repository --yes --update ppa:ansible/ansible"
  become: true
  become_user: root

- name: Install ansible
  apt:
    name: ansible
    state: present
  become: true
  become_user: root

- name: Install python-pip
  apt:
    name: python-pip
    state: present
  become: true
  become_user: root

- name: Install python-setuptools
  apt:
    name: python-setuptools
    state: present
  become: true
  become_user: root

- name: Install git
  apt:
    name: git
    state: present
  become: true
  become_user: root
