name: Ansible Lint

on: [push, pull_request]

jobs:
  Lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Lint Ansible Playbook
      uses: ansible/ansible-lint-action@151b9a2
      with:
        # If you want to lint multiple ansible files, use the following syntax
        # targets: |
        #   playbook_1.yml
        #   playbook_2.yml
        targets: "./*.yml"
        args: " -x 204,403,301,305,701,401"
